// Code generated by protoc-gen-go.
// source: mcc.proto
// DO NOT EDIT!

/*
Package mcc is a generated protocol buffer package.

It is generated from these files:
	mcc.proto

It has these top-level messages:
	RegisterRequest
	RegisterResponse
	JoinRequest
	JoinResponse
	HeartBeatRequest
	HeartBeatResponse
	LookupRequest
	LookupResponse
*/
package mcc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 注册服务 - 请求
type RegisterRequest struct {
	// 服务唯一名称
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// 服务描述
	Desc string `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 注册服务 - 返回
type RegisterResponse struct {
	// 服务的apptoken，用于增加服务器
	AppToken string `protobuf:"bytes,1,opt,name=appToken" json:"appToken,omitempty"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 加入服务的集群 - 请求
type JoinRequest struct {
	// 服务的token
	AppToken string `protobuf:"bytes,1,opt,name=appToken" json:"appToken,omitempty"`
	// 自己的地址
	Addr string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
	// 自己的权重
	Weight int32 `protobuf:"varint,3,opt,name=weight" json:"weight,omitempty"`
}

func (m *JoinRequest) Reset()                    { *m = JoinRequest{} }
func (m *JoinRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()               {}
func (*JoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 加入服务的集群 - 返回
type JoinResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *JoinResponse) Reset()                    { *m = JoinResponse{} }
func (m *JoinResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()               {}
func (*JoinResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 心跳 - 请求
type HeartBeatRequest struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *HeartBeatRequest) Reset()                    { *m = HeartBeatRequest{} }
func (m *HeartBeatRequest) String() string            { return proto.CompactTextString(m) }
func (*HeartBeatRequest) ProtoMessage()               {}
func (*HeartBeatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// 心跳 - 返回
type HeartBeatResponse struct {
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
}

func (m *HeartBeatResponse) Reset()                    { *m = HeartBeatResponse{} }
func (m *HeartBeatResponse) String() string            { return proto.CompactTextString(m) }
func (*HeartBeatResponse) ProtoMessage()               {}
func (*HeartBeatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// 查找服务 - 请求
type LookupRequest struct {
	// 服务名称
	ServiceName string `protobuf:"bytes,1,opt,name=serviceName" json:"serviceName,omitempty"`
}

func (m *LookupRequest) Reset()                    { *m = LookupRequest{} }
func (m *LookupRequest) String() string            { return proto.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()               {}
func (*LookupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// 查找服务 - 返回
type LookupResponse struct {
	// 服务地址
	ServiceAddr string `protobuf:"bytes,1,opt,name=serviceAddr" json:"serviceAddr,omitempty"`
}

func (m *LookupResponse) Reset()                    { *m = LookupResponse{} }
func (m *LookupResponse) String() string            { return proto.CompactTextString(m) }
func (*LookupResponse) ProtoMessage()               {}
func (*LookupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
	proto.RegisterType((*JoinRequest)(nil), "JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "JoinResponse")
	proto.RegisterType((*HeartBeatRequest)(nil), "HeartBeatRequest")
	proto.RegisterType((*HeartBeatResponse)(nil), "HeartBeatResponse")
	proto.RegisterType((*LookupRequest)(nil), "LookupRequest")
	proto.RegisterType((*LookupResponse)(nil), "LookupResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Mcc service

type MccClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	HeartBeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*HeartBeatResponse, error)
}

type mccClient struct {
	cc *grpc.ClientConn
}

func NewMccClient(cc *grpc.ClientConn) MccClient {
	return &mccClient{cc}
}

func (c *mccClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := grpc.Invoke(ctx, "/Mcc/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mccClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	out := new(LookupResponse)
	err := grpc.Invoke(ctx, "/Mcc/Lookup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mccClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := grpc.Invoke(ctx, "/Mcc/Join", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mccClient) HeartBeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*HeartBeatResponse, error) {
	out := new(HeartBeatResponse)
	err := grpc.Invoke(ctx, "/Mcc/HeartBeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Mcc service

type MccServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Lookup(context.Context, *LookupRequest) (*LookupResponse, error)
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	HeartBeat(context.Context, *HeartBeatRequest) (*HeartBeatResponse, error)
}

func RegisterMccServer(s *grpc.Server, srv MccServer) {
	s.RegisterService(&_Mcc_serviceDesc, srv)
}

func _Mcc_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MccServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Mcc/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MccServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcc_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MccServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Mcc/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MccServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcc_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MccServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Mcc/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MccServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcc_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MccServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Mcc/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MccServer).HeartBeat(ctx, req.(*HeartBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mcc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Mcc",
	HandlerType: (*MccServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Mcc_Register_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _Mcc_Lookup_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _Mcc_Join_Handler,
		},
		{
			MethodName: "HeartBeat",
			Handler:    _Mcc_HeartBeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("mcc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x52, 0x4b, 0x6b, 0xdb, 0x40,
	0x10, 0x96, 0x6a, 0x5b, 0xb5, 0xc7, 0xef, 0x3d, 0xb8, 0x42, 0x27, 0xb3, 0x50, 0x6a, 0xda, 0xb2,
	0x60, 0xb7, 0x97, 0x1e, 0x6b, 0x5f, 0x4a, 0xa9, 0x4b, 0x10, 0xc9, 0x39, 0x6c, 0x56, 0x83, 0x22,
	0x1c, 0xed, 0x2a, 0xbb, 0xab, 0xe4, 0xff, 0xe5, 0x97, 0x05, 0xbd, 0x6c, 0xd9, 0x81, 0xdc, 0x66,
	0x46, 0xf3, 0x3d, 0xf4, 0xcd, 0xc2, 0x20, 0x15, 0x82, 0x65, 0x5a, 0x59, 0x45, 0x7f, 0xc1, 0x34,
	0xc4, 0x38, 0x31, 0x16, 0x75, 0x88, 0x8f, 0x39, 0x1a, 0x4b, 0x08, 0x74, 0x25, 0x4f, 0xd1, 0x77,
	0x97, 0xee, 0x6a, 0x10, 0x96, 0x75, 0x31, 0x8b, 0xd0, 0x08, 0xff, 0x43, 0x35, 0x2b, 0x6a, 0xca,
	0x60, 0x76, 0x82, 0x9a, 0x4c, 0x49, 0x83, 0x24, 0x80, 0x3e, 0xcf, 0xb2, 0x6b, 0x75, 0x40, 0x59,
	0xe3, 0x8f, 0x3d, 0xbd, 0x81, 0xe1, 0x5f, 0x95, 0xc8, 0x46, 0xe6, 0x9d, 0xd5, 0x42, 0x8e, 0x47,
	0x91, 0x6e, 0xe4, 0x8a, 0x9a, 0x2c, 0xc0, 0x7b, 0xc6, 0x24, 0xbe, 0xb7, 0x7e, 0x67, 0xe9, 0xae,
	0x7a, 0x61, 0xdd, 0xd1, 0x15, 0x8c, 0x2a, 0xda, 0xda, 0x82, 0x0f, 0x1f, 0x4d, 0x2e, 0x04, 0x1a,
	0x53, 0xd2, 0xf6, 0xc3, 0xa6, 0xa5, 0x5f, 0x61, 0xf6, 0x07, 0xb9, 0xb6, 0x5b, 0xe4, 0xb6, 0x71,
	0xb1, 0x00, 0xcf, 0x58, 0x6e, 0xf3, 0x6a, 0xb9, 0x17, 0xd6, 0x1d, 0xfd, 0x02, 0xf3, 0xd6, 0x6e,
	0x4d, 0x4d, 0xa0, 0x2b, 0x54, 0x84, 0xf5, 0x6a, 0x59, 0xd3, 0x35, 0x8c, 0xff, 0x29, 0x75, 0xc8,
	0xb3, 0x86, 0x71, 0x09, 0x43, 0x83, 0xfa, 0x29, 0x11, 0xf8, 0xff, 0x94, 0x62, 0x7b, 0x44, 0x37,
	0x30, 0x69, 0x20, 0x35, 0xf1, 0x09, 0xf3, 0xbb, 0xf8, 0xed, 0x73, 0x4c, 0x31, 0xda, 0xbc, 0xb8,
	0xd0, 0xd9, 0x0b, 0x41, 0xd6, 0xd0, 0x6f, 0x42, 0x27, 0x33, 0x76, 0x71, 0xba, 0x60, 0xce, 0x2e,
	0x2f, 0x42, 0x1d, 0xf2, 0x0d, 0xbc, 0x4a, 0x8e, 0x4c, 0xd8, 0x99, 0xd5, 0x60, 0xca, 0xce, 0x7d,
	0x50, 0x87, 0x7c, 0x86, 0x6e, 0x91, 0x26, 0x19, 0xb1, 0xd6, 0xad, 0x82, 0x31, 0x6b, 0x47, 0x4c,
	0x1d, 0xf2, 0x13, 0x06, 0xc7, 0x78, 0xc8, 0x9c, 0x5d, 0xc6, 0x1a, 0x10, 0xf6, 0x26, 0x3d, 0xea,
	0x6c, 0xbf, 0xc3, 0x34, 0xd6, 0x99, 0xb8, 0x15, 0x28, 0x2d, 0x6a, 0x96, 0x0a, 0xb1, 0xfd, 0xb4,
	0xe7, 0x92, 0xc7, 0x98, 0xa2, 0xb4, 0x3b, 0x25, 0xad, 0x56, 0x0f, 0xbb, 0xf2, 0xe3, 0x95, 0x7b,
	0xe7, 0x95, 0x2f, 0xf4, 0xc7, 0x6b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x07, 0xb7, 0x41, 0xae,
	0x02, 0x00, 0x00,
}
